### ISSUE TITLE
Server instance init

### ISSUE THREAD

**Issue by totogo** [alax/jsrp#12]
If I describe it correctly, the client side needs to communicate with server side for at least 3 times
1. Send the identifier and get the salt
2. Send the cPubKey and get the sPubKey
3. Send the M1 value to server and get the checking result

My issue here is that on server side each time when I get a request from client app, I need to init the jsrp server instance, then seems the instance is always different from previous one. So when I ```s.checkClientProof(M1)```, the result is always not true. 

How do you persist the server instance? Sorry I am pretty new on this. Thanks in advance for your guidance.

**Comment by alax** [comment]
You need to create the client verifier and salt, and send both of those to the server. When you'd like to verify the client, you need to call server.init() with both the verifier and the salt that was sent by the client previously.

**Comment by totogo** [comment]
Thanks for your feedback. 
Sorry, I meant for login process. The registration process is OK. When I do login, the client app needs to 
1. send the identifier and client public key to server, then get back the salt and server public key. 
2. set salt and server public key, then send proof (M1) to server. 

On server side, I receive 2 times of requests from client app. The ```server.init()``` is called twice. And each time when I call ```server.init()``` even with the same salt and verifier, I got different result. So I can't get true when I call ```server.checkClientProof(M1)```. 

I went through the coffee script, and I finally had a solution, which may not be a good one. I extracted the random number from the instance ```server.bInt``` in 1st request, saved it to the DB. Then 2nd time when I call initiate server instance, I use ```server.debugInit({salt: '...', verifier: '...', b: '...'})``` to pass the random number through ```b```. 

It works, but I don't feel like it is the best way to do it. Do you have any suggestion?

**Comment by alax** [comment]
Sorry for the late response. Would you mind posting a working example of the code that is causing issues for you? The tests still work on the latest version of Node, so I am inclined to think this is not an issue with the library. I could definitely be wrong though, so please let me know. Thanks!

**Comment by kind3r** [comment]
I have the exact same issue and the only way to solve it is to use `server.debugInit()` to restore previously generated public/private key pair after saving it using `transform.bigInt.toBuffer(server.bInt)`. I think this should be implemented directly in the server's init method along with a `getPrivateKey()` method so we don't have to include `transform.js`.

For a stateless app (like an AWS Lambda function), the client would have to make 2 requests to authenticate so there would be 2 separate server instances (one for each call) and the 2nd instance would have to restore the randomly generated keys (SRP_b and SRP_B) from the first request.

The following image taken from https://bitbucket.org/simon_massey/thinbus-srp-js illustrates this:
![login](https://cloud.githubusercontent.com/assets/1621814/22860274/732f39bc-f101-11e6-9386-db21df9c8226.png)

Sample code for server side **login.html** (1st request):
```JavaScript
var server = new jsrp.server();
// fetch salt and verifier using client provided username (email in our example)
server.init({salt: 'SALT_FROM_DB', verifier: 'VERIFIER_FROM_DB'}, function () {
  // return server public key (SRP_B) and salt to client
  console.log(server.getPublicKey());
  console.log(server.getSalt());
  // save generated private key in a session
  console.log(transform.bigInt.toBuffer(server.bInt));
});
```

Client computes proof M1 and sends it together with SRP_A and username (email in our example).
Sample code for server side **authenticate** (2nd request):
```JavaScript
var server = new jsrp.server();
// fetch salt and verifier using client provided username (email in our example)
// restore the private key from session
server.debugInit({salt: 'SALT_FROM_DB', verifier: 'VERIFIER_FROM_DB', b: 'PRIVATE_KEY_FROM_SESSION'}, function() {
  // set public key received from client
  server.setClientPublicKey(SRP_A);
  // check if client sent proof matches
  if(server.checkClientProof(proofM1)) {
    console.log('Proof matches server OK');
  } else {
    console.log('Proof did not match server');
  }
});
```

**Comment by alax** [comment]
Oh! Okay, I totally misunderstood the issue. Yes, I see what you mean now. Thanks for the pull request, I've merged it and I will update the NPM package here shortly.

**Comment by dangtony98** [comment]
Would definitely add this to the README.md somewhere. I spent sometime trying to figure out why client/server sharedKeys; turned out that b was missing — would add that bigint-conversion helped.
