### ISSUE TITLE
the length of hex string is required to be even number

### ISSUE THREAD

**Issue by jackiszhp** [alax/jsrp#16]
In the buffer module, the hexWrite throws "Invalid hex string" if the length of the hex string is not an even number. In java, for example BigInteger(15).toString(16) will gives "f", its length is odd(1), so hex string should be checked before being passed into jsrp, and in turn to buffer.

==============================
function hexWrite (buf, string, offset, length) {
  offset = Number(offset) || 0
  var remaining = buf.length - offset
  if (!length) {
    length = remaining
  } else {
    length = Number(length)
    if (length > remaining) {
      length = remaining
    }
  }

  // must be an even number of digits
  var strLen = string.length
  if (strLen % 2 !== 0) throw new TypeError('Invalid hex string')

**Comment by poursal** [comment]
@alax Fixed in #20
