### ISSUE TITLE
jsbn dependency should be updated from 0.1.0 to 1.1.0

### ISSUE THREAD

**Issue by grempe** [alax/jsrp#18]
There has been a cleanup and new release in the jsbn project which you should follow.

You currently depend on `v0.1.0` which should be updated in `package.json` to be `1.1.0`. This will allow you to pick up future bugfixes while the 0.1.0 branch is now likely a dead-end.

See: https://github.com/andyperlitch/jsbn/issues/14 for more info.

**Comment by poursal** [comment]
@alax Fixed in #20
