### ISSUE TITLE
Compatible Golang implementation with JSRP?

### ISSUE THREAD

**Issue by dangtony98** [alax/jsrp#25]
Hi there!

We're building a platform using this package on the backend. We're working on an accompanying CLI written in Go and wanted something that's compatible but haven't been able to find any compatible implementations in Go — Is there any that you could recommend?

Also, does this package only conform to the specification in RFC 2945 or also RFC 5054?

Thanks!

**Comment by dangtony98** [comment]
Nevermind. Solved the compatibility issue after referencing the issue #22 — It seems that the M1 calculation does differ (JSRP implements SRP as specified on Wikipedia which differs from RFC 2945 in the final M1 computation step).

**Comment by arthur-trt** [comment]
@dangtony98 I've seen in issue #22 that you've modified the kong/go-srp library to be compatible with jsrp. Could you share your modifications? I'm having the same problem. 

Thanks a lot!
