### ISSUE TITLE
Generator param for 8192-bit Group is incorrect

### ISSUE THREAD

**Issue by grempe** [alax/jsrp#4]
It appears that the generator param for 8192 bits is incorrect here:

https://github.com/alax/jsrp/blob/master/src/parameters.coffee#L128

The spec calls for this value to be `19`

https://tools.ietf.org/html/rfc5054#appendix-A

Thanks

**Comment by alax** [comment]
Thanks for the report! If you look take a look here:

https://github.com/alax/jsrp/blob/master/src/parameters.coffee#L169

You'll see that the generator is specified in hexadecimal in my code. The spec calls for the value to be `19` in decimal, which is the value `13` in hexadecimal. Thanks!

**Comment by grempe** [comment]
Indeed!  Thanks for the quick clarification.
