### ISSUE TITLE
New SiRP Ruby Gem Review Requested, tested with jsrp 

### ISSUE THREAD

**Issue by grempe** [alax/jsrp#5]
Hello,

I've just published a pre-release version of a new Ruby Gem which implements SRP. I needed this code to be interoperable with Ruby clients and also at least one JavaScript client.  I chose to use your `jsrp` lib as the initial test case to implement against.

I would be grateful if you could take a look at it and maybe kick the tires a bit.

You can find it here:

https://github.com/grempe/sirp/blob/master/README.md

And the example server and client are in the `examples` dir.

https://github.com/grempe/sirp/tree/master/examples

Once you start the server you should be able to just open the `index.html` file to run the client with your jsrp code against the server.

Thanks again, and please feel free to share any issues you run into or suggestions.

https://github.com/grempe/sirp/issues

Glenn

**Comment by grempe** [comment]
FYI, I have removed the example code I mentioned above from the grempe/sirp repository. Instead there is now a live demo site running on Heroku using this JSRP package and my SIRP Ruby gem.

https://sirp-demo.herokuapp.com/index.html

The code for that demo is here and includes improved versions of the example code:

https://github.com/grempe/sirp-demo

This may not be a bad resource for your users since it is a fully functional demo in basic HTML and JS including a user registration process and all state is stored on the server side in a Redis DB.

Happy to hear any feedback on changes I could make to improve.

Cheers

**Comment by alax** [comment]
Thanks for the contribution! I am not a Ruby developer, so I am afraid I cannot offer much help. But I do appreciate the work you've done to make this protocol and package even more accessible.
